### ISSUE TITLE
Google sheet export bug

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/dataset#10]
dataset -c CompletedTheses export-gsheet 1SUz1FfQNr3dpnbrwGsBofPsuqinOM7EBmrGOvVJM_yE Sheet1 A1:CZ true .done,.key,.resolver,.subjects,.additional,.identifier_1,.description_1,.identifier_2,.description_2,.identifier_3,.description_3,.identifier_4,.description_4,.identifier_5,.description_5,.identifier_6,.description_6,.identifier_7,.description_7,.identifier_8,.description_8,.identifier_9,.description_9,.identifier_10,.description_10,.identifier_11,.description_11,.identifier_12,.description_12,.identifier_13,.description_13,.identifier_14,.description_14,.identifier_15,.description_15,.identifier_16,.description_16,.identifier_17,.description_17,.identifier_18,.description_18,.identifier_19,.description_19,.identifier_20,.description_20 done,key,resolver,subjects,additional,identifier_1,description_1,identifier_2,description_2,identifier_3,description_3,identifier_4,description_4,identifier_5,description_5,identifier_6,description_6,identifier_7,description_7,identifier_8,description_8,identifier_9,description_9,identifier_10,description_10,identifier_11,description_11,identifier_12,description_12,identifier_13,description_13,identifier_14,description_14,identifier_15,description_15,identifier_16,description_16,identifier_17,description_17,identifier_18,description_18,identifier_19,description_19,identifier_20,description_20

https://docs.google.com/spreadsheets/d/1SUz1FfQNr3dpnbrwGsBofPsuqinOM7EBmrGOvVJM_yE/edit#gid=0

[CompletedTheses.zip](https://github.com/caltechlibrary/dataset/files/1717939/CompletedTheses.zip)

This command works on dataset v0.0.13

**Comment by rsdoiel** [comment]
I have fixed the array over run error when handling parameters for export-gsheet.  I would like you to re-test against the pre-release v0.0.20-dev before closing this issue. I must not have the right client_secret.json file because I get an OAuth permission denied error when I run against your test example.

**Comment by tmorrell** [comment]
I'm still not getting any fields exported.  You can swap out the google sheet ID for a new sheet Here is a simplified example:

dataset init test

export DATASET=test

dataset create test '{"additional":"Supplemental Files Information:\nGeologic Plate: Supplement 1 from \"The geology of a portion of the Repetto Hills\" (Thesis)\n","description_1":"Supplement 1 in CaltechDATA: Geologic Plate","done":"yes","identifier_1":"https://doi.org/10.22002/D1.638","key":"Wilson1930","resolver":"http://resolver.caltech.edu/CaltechTHESIS:12032009-111148185","subjects":"Repetto Hills, Coyote Pass, sandstones, shales"}'

dataset export-gsheet 1qRAssKXx2nK-yhIrKOmUEahhVzD_d_JUrWs_PabmJQI Sheet1 A1:CZ true .done,.key,.resolver,.additional,.identifier_1,.description_1 done,key,resolver,subjects,additional,identifier_1,description_1

**Comment by tmorrell** [comment]
Fixed in today's release
